export const OPEN_USER_INFO_MODAL = "OPEN_USER_INFO_MODAL";
export const CLOSE_USER_INFO_MODAL = "CLOSE_USER_INFO_MODAL";
export const OPEN_FILTR_PROJECTS_MODAL = "OPEN_FILTR_PROJECTS_MODAL";
export const CLOSE_FILTR_PROJECTS_MODAL = "CLOSE_FILTR_PROJECTS_MODAL";
export const OPEN_DELETE_PROJECT_MODAL = "OPEN_DELETE_PROJECT_MODAL";
export const CLOSE_DELETE_PROJECT_MODAL = "CLOSE_DELETE_PROJECT_MODAL";
