export const OPEN_USER_INFO = "OPEN_USER_INFO";
export const CLOSE_USER_INFO = "CLOSE_USER_INFO";
export const OPEN_FILTR_PROJECTS = "OPEN_FILTR_PROJECTS";
export const CLOSE_FILTR_PROJECTS = "CLOSE_FILTR_PROJECTS";
